// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfidngsnqyjaydzhilxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmaWRuZ3NucXlqYXlkemhpbHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzg2NDMsImV4cCI6MjA2MjY1NDY0M30.gw0wiR3wwE4utv5sK4KyFiDNR-APwNdcvMsXDZOibzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);